/**
 * Building blocks for the route schemas.
 *
 * A declared schema is what keeps a JSON body from reaching a Mongo filter as
 * something other than the scalar it is meant to be. Without one, `{"$ne": null}`
 * sent where a token is expected arrives at the handler as an object and becomes a
 * query operator: the TypeScript types on the route generics are erased at compile
 * time and validate nothing at runtime.
 *
 * Three behaviours of the Fastify defaults are load-bearing here, and the helpers
 * below are shaped around them:
 *
 * - `removeAdditional` strips whatever `additionalProperties: false` does not
 *   declare, instead of rejecting the request. A strict object therefore silently
 *   drops unknown fields, which is the mass-assignment defence but also means an
 *   under-declared schema loses data. Use `strictBody` only where the field list is
 *   known in full, and `openBody` everywhere the payload carries provider-shaped
 *   or free-form data.
 * - `coerceTypes` turns `12` into `"12"` for a string field and unwraps a
 *   single-element array, but never turns an object into a string. The coercion is
 *   a convenience for form-encoded clients; the type check is the defence.
 * - A failed validation is a `FST_ERR_VALIDATION` error with status 400, which the
 *   error handler plugin passes through untouched.
 */

/** A Mongo ObjectId as it travels in a URL or a JSON body. */
export const objectId = {
    type: "string",
    pattern: "^[0-9a-fA-F]{24}$"
} as const

export const objectIdArray = {
    type: "array",
    items: objectId
} as const

/**
 * A human-typed single-line value: a name, a slug, a branch, a label.
 *
 * The upper bound is not a business rule, it is what keeps an unbounded string out
 * of the database and out of the regexes and path joins downstream.
 */
export const shortText = (maxLength = 255) =>
    ({
        type: "string",
        maxLength
    }) as const

export const requiredShortText = (maxLength = 255) =>
    ({
        type: "string",
        minLength: 1,
        maxLength
    }) as const

export const longText = (maxLength = 4096) =>
    ({
        type: "string",
        maxLength
    }) as const

export const email = {
    type: "string",
    format: "email",
    maxLength: 320
} as const

/**
 * A secret generated by this platform or by a provider: reset and activation
 * tokens, invitation tokens, OAuth codes, personal access tokens.
 *
 * Only the shape is constrained. The value is opaque and is checked by whoever
 * issued it; what matters here is that it arrives as a string.
 */
export const secretString = (maxLength = 4096) =>
    ({
        type: "string",
        minLength: 1,
        maxLength
    }) as const

/** At least eight characters, the bound the user model already enforces on save. */
export const password = {
    type: "string",
    minLength: 8,
    maxLength: 256
} as const

export const boolean = { type: "boolean" } as const

export const integer = (minimum?: number, maximum?: number) =>
    ({
        type: "integer",
        ...(minimum !== undefined && { minimum }),
        ...(maximum !== undefined && { maximum })
    }) as const

export const number = (minimum?: number, maximum?: number) =>
    ({
        type: "number",
        ...(minimum !== undefined && { minimum }),
        ...(maximum !== undefined && { maximum })
    }) as const

export const stringArray = (maxLength = 255) =>
    ({
        type: "array",
        items: shortText(maxLength)
    }) as const

export const enumOf = (values: readonly string[]) =>
    ({
        type: "string",
        enum: [...values]
    }) as const

/** ISO date or timestamp, accepted in either of the forms the clients send. */
export const dateLike = {
    type: "string",
    minLength: 1,
    maxLength: 64
} as const

type Properties = Record<string, unknown>

/**
 * Route parameters. They are always present by virtue of the route matching, so
 * every declared one is required, and nothing else can appear.
 */
export const params = (properties: Properties) =>
    ({
        type: "object",
        required: Object.keys(properties),
        additionalProperties: false,
        properties
    }) as const

/**
 * Query string. Left open on purpose: the frontend appends UTM parameters to any
 * request it wants attributed, and they must travel without being declared route
 * by route.
 */
export const query = (properties: Properties, required: readonly string[] = []) =>
    ({
        type: "object",
        ...(required.length > 0 && { required: [...required] }),
        properties
    }) as const

/**
 * A body whose fields are known in full. Anything undeclared is dropped before the
 * handler sees it, which is what stops a public endpoint from being handed a field
 * the client was never meant to set.
 */
export const strictBody = (properties: Properties, required: readonly string[] = []) =>
    ({
        type: "object",
        ...(required.length > 0 && { required: [...required] }),
        additionalProperties: false,
        properties
    }) as const

/**
 * A body that carries data this platform does not own the shape of — a cloud
 * provider credential blob, a nested microfrontend descriptor. The declared fields
 * are still type-checked, undeclared ones are passed through rather than dropped,
 * so a payload that grows on the client does not silently lose fields here.
 */
export const openBody = (properties: Properties, required: readonly string[] = []) =>
    ({
        type: "object",
        ...(required.length > 0 && { required: [...required] }),
        properties
    }) as const

/** A body that is a bare array, as a few bulk endpoints take. */
export const arrayBody = (items: unknown) =>
    ({
        type: "array",
        items
    }) as const
