import { CodeBlock } from "@mfe-orchestrator/design-system"
import { useQuery } from "@tanstack/react-query"
import { useTranslation } from "react-i18next"
import { ApiStatusHandler } from "@/components/organisms"
import useServeApi, { MicrofrontendCompiler, MicrofrontendFramework } from "@/hooks/apiClients/useServeApi"
import StackBadge from "./StackBadge"

export interface CodeIntegrationProps {
    microfrontendId: string
    deploymentId: string
    /** Overrides of the stack stored on the microfrontend, when the user picks another one */
    framework?: MicrofrontendFramework
    compiler?: MicrofrontendCompiler
}

/**
 * The integration instructions of one microfrontend, generated by the backend for the stack it is
 * built with: which packages to install, which config file to write, and where.
 */
export const CodeIntegration: React.FC<CodeIntegrationProps> = ({ microfrontendId, deploymentId, framework, compiler }) => {
    const { t } = useTranslation()
    const serveApi = useServeApi()

    const codeQuery = useQuery({
        queryKey: ["code", microfrontendId, deploymentId, framework, compiler],
        queryFn: () => serveApi.getCodeIntegration({ microfrontendId, deploymentId, framework, compiler })
    })

    const instructions = codeQuery.data

    return (
        <ApiStatusHandler queries={[codeQuery]}>
            {instructions && (
                <div className="flex flex-col gap-4">
                    <StackBadge stack={instructions.stack} />

                    {!instructions.runtimeIntegration && !instructions.code && (
                        <div>
                            <h4 className="text-base font-semibold">{t("integration.fe_integration_tab.stack_unknown_title")}</h4>
                            <p>{t("integration.fe_integration_tab.stack_unknown_description")}</p>
                        </div>
                    )}

                    {instructions.runtimeIntegration ? (
                        <div>
                            <h4 className="text-base font-semibold">{t("integration.fe_integration_tab.runtime_integration_title")}</h4>
                            <p>{t("integration.fe_integration_tab.runtime_integration_description")}</p>
                        </div>
                    ) : (
                        <>
                            {instructions.installCommand && (
                                <CodeBlock
                                    label={t("integration.fe_integration_tab.install_step")}
                                    code={instructions.installCommand}
                                    copyable
                                    copyLabel={t("common.copy")}
                                    copiedLabel={t("common.copied")}
                                />
                            )}

                            {instructions.code && (
                                <CodeBlock
                                    label={t("integration.fe_integration_tab.config_step", { path: instructions.configPath })}
                                    code={instructions.code}
                                    copyable
                                    copyLabel={t("common.copy")}
                                    copiedLabel={t("common.copied")}
                                />
                            )}
                        </>
                    )}
                </div>
            )}
        </ApiStatusHandler>
    )
}

export default CodeIntegration
