{{- if include "mfe-orchestrator.hasEnvEntries" (.Values.envSecrets | default dict) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mfe-orchestrator.fullname" . }}-env
  labels:
    {{- include "mfe-orchestrator.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  {{- include "mfe-orchestrator.envEntries" (.Values.envSecrets | default dict) | trim | nindent 2 }}
{{- end }}
