name: 🚀 Deploy to Server

permissions:
  contents: read

on:
  push:
    branches: [main]
    tags: ['*']

    
jobs:
  docker-build:
    uses: ./.github/workflows/docker-build.yml
    secrets: inherit

  deploy:
    needs: [docker-build]
    runs-on: ubuntu-latest

    steps:
    - name: 🚀 Deploy to DEV
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          cd ${{ secrets.TERRAFORM_PATH }}
          tofu init
          tofu apply -auto-approve
