name: 🐳 Docker Build

permissions:
  contents: read
on:
  workflow_call:
  push:
    branches: [main]
    tags: ["*"]

jobs:
  monorepo-build:
    uses: ./.github/workflows/monorepo-build.yml
    secrets: inherit

  docker-build:
    needs: [monorepo-build]
    runs-on: ubuntu-latest

    steps:
      - name: 🔄 Checkout
        uses: actions/checkout@v7

      - name: 📥 Download Backend Build
        uses: actions/download-artifact@v8
        with:
          name: backend-build
          path: backend/dist

      - name: 📥 Download Frontend Build
        uses: actions/download-artifact@v8
        with:
          name: frontend-build
          path: frontend/dist

      - name: 🔑 Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 🚀 Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/mfe-orchestrator:latest -f Dockerfile .
          
          if [[ "${{ github.ref_type }}" == "tag" ]]; then
            docker tag ${{ secrets.DOCKERHUB_USERNAME }}/mfe-orchestrator:latest ${{ secrets.DOCKERHUB_USERNAME }}/mfe-orchestrator:${{ github.ref_name }}
            docker push ${{ secrets.DOCKERHUB_USERNAME }}/mfe-orchestrator:${{ github.ref_name }}
          else
            docker push ${{ secrets.DOCKERHUB_USERNAME }}/mfe-orchestrator:latest
          fi
